// angular-app/src/app/app.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  SimpleChanges,
} from '@angular/core';
import angularLogo from '../assets/angular.png';

type Data = {
  channel: string;
  data: any;
};

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  angularLogo = angularLogo;
  @Input() inputData!: Data;
  @Output() outputData = new EventEmitter<Data>();

  stringify = JSON.stringify;

  _inputData?: Data;

  handleClick() {
    this.outputData.emit({
      channel: 'ANGULAR_WIDGET',
      data: 'Hello from Angular',
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['inputData'] && changes['inputData'].currentValue) {
      this._inputData = changes['inputData'].currentValue;
    }
  }
}

<img [src]="angularLogo" alt="Angular Logo" style="height: 6rem;" />
<h2>Input Data</h2>
<pre>{{ stringify(_inputData, null, 2) }}</pre>
<button (click)="handleClick()">Click me!</button>

// react-app/src/App.tsx
import "./App.css";
import reactLogo from "../public/react.svg?inline";
import rsPackLogo from "../public/rspack.png";

export type Data = {
  channel: string;
  data: any;
};

interface IProps {
  inputData: Data;
  outputData: (data: Data) => void;
}

const App = (props: IProps) => {
  return (
    <div className="content">
      <div>
        <img src={reactLogo} alt="React Logo" width={50} />
      </div>
      <h2>Input Data</h2>
      <pre>{JSON.stringify(props.inputData, null, 2)}</pre>
      <div>
        <button
          onClick={() =>
            props.outputData({
              channel: "REACT_WIDGET",
              data: "Hello from React",
            })
          }
        >
          Click me
        </button>
      </div>
    </div>
  );
};

export default App;
